ARG RUST_VERSION=1.64
FROM rust:${RUST_VERSION}-slim-bullseye

RUN apt update \
    && apt install --yes pkg-config openssl libssl-dev g++ cmake git curl

RUN git clone -b v22.9.29 --depth 1 https://github.com/google/flatbuffers.git && cd flatbuffers \
    && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
    && make install && cd .. && rm -rf flatbuffers

# Install protobuf-compiler
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip && \
     unzip protoc-3.15.8-linux-x86_64.zip -d $HOME/ && mv $HOME/bin/protoc /usr/bin/protoc