FROM --platform=$BUILDPLATFORM golang:1.17.5 as builder
ARG TARGETARCH

WORKDIR /go/src/github.com/cnosdb/cnosdb
COPY . /go/src/github.com/cnosdb/cnosdb

# Proxy, You know.
RUN go env -w GOPROXY=https://goproxy.cn,direct

RUN GOOS=linux GOARCH=$TARGETARCH go install ./...

FROM debian:stretch
COPY --from=builder /go/bin/cnosdb-meta /go/bin/cnosdb-ctl /usr/bin/
COPY --from=builder /go/src/github.com/cnosdb/cnosdb/etc/cnosdb-meta.sample.toml /etc/cnosdb/cnosdb-meta.conf

EXPOSE 8091
VOLUME /var/lib/cnosdb

COPY docker/entrypoint.sh /entrypoint.sh
COPY docker/init-cnosdb.sh /init-cnosdb.sh
RUN chmod +x /entrypoint.sh /init-cnosdb.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["cnosdb-meta","--config","/etc/cnosdb/cnosdb-meta.conf"]