// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/data.proto

package internal

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WriteShardRequest struct {
	ShardID              *uint64  `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Points               [][]byte `protobuf:"bytes,2,rep,name=Points" json:"Points,omitempty"`
	Database             *string  `protobuf:"bytes,3,opt,name=Database" json:"Database,omitempty"`
	RetentionPolicy      *string  `protobuf:"bytes,4,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteShardRequest) Reset()         { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()    {}
func (*WriteShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{0}
}
func (m *WriteShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteShardRequest.Unmarshal(m, b)
}
func (m *WriteShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteShardRequest.Marshal(b, m, deterministic)
}
func (m *WriteShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteShardRequest.Merge(m, src)
}
func (m *WriteShardRequest) XXX_Size() int {
	return xxx_messageInfo_WriteShardRequest.Size(m)
}
func (m *WriteShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteShardRequest proto.InternalMessageInfo

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetPoints() [][]byte {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *WriteShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *WriteShardRequest) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

type WriteShardResponse struct {
	Code                 *int32   `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteShardResponse) Reset()         { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()    {}
func (*WriteShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{1}
}
func (m *WriteShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteShardResponse.Unmarshal(m, b)
}
func (m *WriteShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteShardResponse.Marshal(b, m, deterministic)
}
func (m *WriteShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteShardResponse.Merge(m, src)
}
func (m *WriteShardResponse) XXX_Size() int {
	return xxx_messageInfo_WriteShardResponse.Size(m)
}
func (m *WriteShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteShardResponse proto.InternalMessageInfo

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ExecuteStatementRequest struct {
	Statement            *string  `protobuf:"bytes,1,req,name=Statement" json:"Statement,omitempty"`
	Database             *string  `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStatementRequest) Reset()         { *m = ExecuteStatementRequest{} }
func (m *ExecuteStatementRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementRequest) ProtoMessage()    {}
func (*ExecuteStatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{2}
}
func (m *ExecuteStatementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementRequest.Unmarshal(m, b)
}
func (m *ExecuteStatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementRequest.Merge(m, src)
}
func (m *ExecuteStatementRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementRequest.Size(m)
}
func (m *ExecuteStatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementRequest proto.InternalMessageInfo

func (m *ExecuteStatementRequest) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *ExecuteStatementRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

type ExecuteStatementResponse struct {
	Code                 *int32   `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message              *string  `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteStatementResponse) Reset()         { *m = ExecuteStatementResponse{} }
func (m *ExecuteStatementResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementResponse) ProtoMessage()    {}
func (*ExecuteStatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{3}
}
func (m *ExecuteStatementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementResponse.Unmarshal(m, b)
}
func (m *ExecuteStatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementResponse.Merge(m, src)
}
func (m *ExecuteStatementResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementResponse.Size(m)
}
func (m *ExecuteStatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementResponse proto.InternalMessageInfo

func (m *ExecuteStatementResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ExecuteStatementResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CreateIteratorRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Opt                  []byte   `protobuf:"bytes,2,req,name=Opt" json:"Opt,omitempty"`
	Database             []byte   `protobuf:"bytes,3,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy      []byte   `protobuf:"bytes,4,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	MeasurementName      []byte   `protobuf:"bytes,5,req,name=MeasurementName" json:"MeasurementName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIteratorRequest) Reset()         { *m = CreateIteratorRequest{} }
func (m *CreateIteratorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorRequest) ProtoMessage()    {}
func (*CreateIteratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{4}
}
func (m *CreateIteratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIteratorRequest.Unmarshal(m, b)
}
func (m *CreateIteratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIteratorRequest.Marshal(b, m, deterministic)
}
func (m *CreateIteratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIteratorRequest.Merge(m, src)
}
func (m *CreateIteratorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIteratorRequest.Size(m)
}
func (m *CreateIteratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIteratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIteratorRequest proto.InternalMessageInfo

func (m *CreateIteratorRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *CreateIteratorRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *CreateIteratorRequest) GetDatabase() []byte {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *CreateIteratorRequest) GetRetentionPolicy() []byte {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

func (m *CreateIteratorRequest) GetMeasurementName() []byte {
	if m != nil {
		return m.MeasurementName
	}
	return nil
}

type CreateIteratorResponse struct {
	Err                  *string  `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	DataType             *int32   `protobuf:"varint,2,opt,name=DataType" json:"DataType,omitempty"`
	SeriesN              *int32   `protobuf:"varint,3,opt,name=SeriesN" json:"SeriesN,omitempty"`
	PointN               *int32   `protobuf:"varint,4,opt,name=PointN" json:"PointN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIteratorResponse) Reset()         { *m = CreateIteratorResponse{} }
func (m *CreateIteratorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorResponse) ProtoMessage()    {}
func (*CreateIteratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{5}
}
func (m *CreateIteratorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIteratorResponse.Unmarshal(m, b)
}
func (m *CreateIteratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIteratorResponse.Marshal(b, m, deterministic)
}
func (m *CreateIteratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIteratorResponse.Merge(m, src)
}
func (m *CreateIteratorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIteratorResponse.Size(m)
}
func (m *CreateIteratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIteratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIteratorResponse proto.InternalMessageInfo

func (m *CreateIteratorResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *CreateIteratorResponse) GetDataType() int32 {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return 0
}

func (m *CreateIteratorResponse) GetSeriesN() int32 {
	if m != nil && m.SeriesN != nil {
		return *m.SeriesN
	}
	return 0
}

func (m *CreateIteratorResponse) GetPointN() int32 {
	if m != nil && m.PointN != nil {
		return *m.PointN
	}
	return 0
}

type FieldDimensionsRequest struct {
	ShardIDs             []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Measurement          []byte   `protobuf:"bytes,2,req,name=Measurement" json:"Measurement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldDimensionsRequest) Reset()         { *m = FieldDimensionsRequest{} }
func (m *FieldDimensionsRequest) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsRequest) ProtoMessage()    {}
func (*FieldDimensionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{6}
}
func (m *FieldDimensionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDimensionsRequest.Unmarshal(m, b)
}
func (m *FieldDimensionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDimensionsRequest.Marshal(b, m, deterministic)
}
func (m *FieldDimensionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDimensionsRequest.Merge(m, src)
}
func (m *FieldDimensionsRequest) XXX_Size() int {
	return xxx_messageInfo_FieldDimensionsRequest.Size(m)
}
func (m *FieldDimensionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDimensionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDimensionsRequest proto.InternalMessageInfo

func (m *FieldDimensionsRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *FieldDimensionsRequest) GetMeasurement() []byte {
	if m != nil {
		return m.Measurement
	}
	return nil
}

type FieldDimensionsResponse struct {
	Fields               []byte   `protobuf:"bytes,1,req,name=Fields" json:"Fields,omitempty"`
	Dimensions           []string `protobuf:"bytes,2,rep,name=Dimensions" json:"Dimensions,omitempty"`
	Err                  *string  `protobuf:"bytes,3,opt,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldDimensionsResponse) Reset()         { *m = FieldDimensionsResponse{} }
func (m *FieldDimensionsResponse) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsResponse) ProtoMessage()    {}
func (*FieldDimensionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7438786364df21e1, []int{7}
}
func (m *FieldDimensionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDimensionsResponse.Unmarshal(m, b)
}
func (m *FieldDimensionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDimensionsResponse.Marshal(b, m, deterministic)
}
func (m *FieldDimensionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDimensionsResponse.Merge(m, src)
}
func (m *FieldDimensionsResponse) XXX_Size() int {
	return xxx_messageInfo_FieldDimensionsResponse.Size(m)
}
func (m *FieldDimensionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDimensionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDimensionsResponse proto.InternalMessageInfo

func (m *FieldDimensionsResponse) GetFields() []byte {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldDimensionsResponse) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *FieldDimensionsResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteShardRequest)(nil), "internal.WriteShardRequest")
	proto.RegisterType((*WriteShardResponse)(nil), "internal.WriteShardResponse")
	proto.RegisterType((*ExecuteStatementRequest)(nil), "internal.ExecuteStatementRequest")
	proto.RegisterType((*ExecuteStatementResponse)(nil), "internal.ExecuteStatementResponse")
	proto.RegisterType((*CreateIteratorRequest)(nil), "internal.CreateIteratorRequest")
	proto.RegisterType((*CreateIteratorResponse)(nil), "internal.CreateIteratorResponse")
	proto.RegisterType((*FieldDimensionsRequest)(nil), "internal.FieldDimensionsRequest")
	proto.RegisterType((*FieldDimensionsResponse)(nil), "internal.FieldDimensionsResponse")
}

func init() { proto.RegisterFile("internal/data.proto", fileDescriptor_7438786364df21e1) }

var fileDescriptor_7438786364df21e1 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x55, 0x36, 0x9b, 0xb2, 0x19, 0x56, 0xa2, 0x18, 0x91, 0x5a, 0x15, 0x42, 0x51, 0x4e, 0x39,
	0xc1, 0x3f, 0xd0, 0x2d, 0xa2, 0x87, 0x86, 0xca, 0x8b, 0xe0, 0x6c, 0x36, 0x23, 0xb0, 0xb4, 0x6b,
	0x07, 0x7b, 0x56, 0x6a, 0xbf, 0x81, 0xef, 0xe1, 0xff, 0x50, 0xa6, 0x71, 0x1a, 0xd2, 0x03, 0x88,
	0xdb, 0xbc, 0xe7, 0xd1, 0xe8, 0xbd, 0x97, 0x17, 0x78, 0x61, 0x2c, 0xa1, 0xb7, 0x7a, 0xff, 0xb6,
	0xd5, 0xa4, 0xdf, 0x74, 0xde, 0x91, 0x13, 0xab, 0x48, 0x56, 0x3f, 0x13, 0x78, 0xfe, 0xc5, 0x1b,
	0xc2, 0xed, 0x77, 0xed, 0x5b, 0x85, 0x3f, 0x8e, 0x18, 0x48, 0x48, 0x78, 0xc2, 0xf8, 0x6a, 0x23,
	0x93, 0x72, 0x51, 0x2f, 0x55, 0x84, 0xa2, 0x80, 0x93, 0x1b, 0x67, 0x2c, 0x05, 0xb9, 0x28, 0xd3,
	0x7a, 0xad, 0x06, 0x24, 0xce, 0x61, 0xb5, 0xd1, 0xa4, 0xbf, 0xea, 0x80, 0x32, 0x2d, 0x93, 0x3a,
	0x57, 0x23, 0x16, 0x35, 0x3c, 0x53, 0x48, 0x68, 0xc9, 0x38, 0x7b, 0xe3, 0xf6, 0x66, 0x77, 0x27,
	0x97, 0xbc, 0x32, 0xa7, 0xab, 0x77, 0x20, 0xa6, 0x62, 0x42, 0xe7, 0x6c, 0x40, 0x21, 0x60, 0x79,
	0xe1, 0x5a, 0x64, 0x29, 0x99, 0xe2, 0xb9, 0x57, 0x78, 0x8d, 0x21, 0xe8, 0x6f, 0x28, 0x17, 0x7c,
	0x2b, 0xc2, 0x6a, 0x0b, 0x67, 0x97, 0xb7, 0xb8, 0x3b, 0x12, 0x6e, 0x49, 0x13, 0x1e, 0xd0, 0x52,
	0xb4, 0xf5, 0x0a, 0xf2, 0x91, 0xe3, 0x6b, 0xb9, 0x7a, 0x20, 0xfe, 0xb0, 0xb0, 0xe0, 0xc7, 0x11,
	0x57, 0x1f, 0x40, 0x3e, 0x3e, 0xfa, 0x5f, 0xf2, 0x7e, 0x25, 0xf0, 0xf2, 0xc2, 0xa3, 0x26, 0xbc,
	0x22, 0xf4, 0x9a, 0x9c, 0x8f, 0xea, 0xce, 0x61, 0x35, 0xa4, 0x1c, 0x64, 0x52, 0xa6, 0xf5, 0x52,
	0x8d, 0x58, 0x9c, 0x42, 0xfa, 0xb1, 0x23, 0x96, 0xb5, 0x56, 0xfd, 0x38, 0x0b, 0xbc, 0xa7, 0xff,
	0x12, 0x78, 0xbf, 0x32, 0xa7, 0xfb, 0xcd, 0x6b, 0xd4, 0xe1, 0xe8, 0xd9, 0x52, 0xa3, 0x0f, 0x28,
	0xb3, 0xfb, 0xcd, 0x19, 0x5d, 0xdd, 0x42, 0x31, 0x97, 0x3d, 0xf8, 0x3f, 0x85, 0xf4, 0xd2, 0x7b,
	0x99, 0xb0, 0xcf, 0x7e, 0x8c, 0xda, 0x3e, 0xdd, 0x75, 0xf7, 0xf6, 0x33, 0x35, 0x62, 0xae, 0x16,
	0x7a, 0x83, 0xa1, 0xe1, 0x9e, 0x64, 0x2a, 0xc2, 0xb1, 0x5a, 0x0d, 0xb7, 0x23, 0x1b, 0xaa, 0xd5,
	0x54, 0x9f, 0xa1, 0x78, 0x6f, 0x70, 0xdf, 0x6e, 0xcc, 0x01, 0x6d, 0x30, 0xce, 0x86, 0x7f, 0x49,
	0xac, 0x84, 0xa7, 0x13, 0x0b, 0x43, 0x72, 0x53, 0xaa, 0xda, 0xc1, 0xd9, 0xa3, 0xbb, 0x83, 0xa5,
	0x02, 0x4e, 0xf8, 0x29, 0xf0, 0x47, 0x5d, 0xab, 0x01, 0x89, 0xd7, 0x00, 0x0f, 0xdb, 0xfc, 0x07,
	0xe4, 0x6a, 0xc2, 0xc4, 0x28, 0xd2, 0x31, 0x8a, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x27,
	0x44, 0xac, 0x7f, 0x03, 0x00, 0x00,
}
