FROM --platform=$TARGETPLATFORM ubuntu

ARG git_hash
ENV CNOSDB_GIT_HASH = $git_hash

ENV RUST_BACKTRACE 1

ARG TARGETPLATFORM
COPY ./$TARGETPLATFORM/cnosdb-meta /usr/bin/cnosdb-meta

COPY ./meta/config/config.toml /etc/cnosdb/cnosdb-meta.conf

CMD ["cnosdb-meta"]
