--#DATABASE=alter_table
DROP DATABASE IF EXISTS alter_table;
CREATE DATABASE alter_table;
CREATE TABLE test (
    f0 BIGINT CODEC(NULL),
    TAGS(t0)
);
ALTER TABLE test DROP f0;
ALTER TABLE test DROP t0;
ALTER TABLE test DROP time;
ALTER TABLE test ADD FIELD time BIGINT;
ALTER TABLE test ADD TAG t0;
ALTER TABLE test ADD FIELD f0 DOUBLE CODEC(DEFAULT);

ALTER TABLE test ADD TAG t1;
DESCRIBE TABLE test;

ALTER TABLE test ADD FIELD f1 BIGINT CODEC(NULL);
DESCRIBE TABLE test;

ALTER TABLE test DROP f0;
ALTER TABLE test DROP f1;
DESCRIBE TABLE test;

ALTER TABLE test ALTER f1 SET CODEC(DEFAULT);
DESCRIBE TABLE test;

ALTER TABLE test ALTER t0 SET CODEC(NULL);

ALTER TABLE test ALTER time SET CODEC(NULL);
DESCRIBE TABLE test;



