--#DATABASE=alter_table
DROP DATABASE IF EXISTS alter_table;
CREATE DATABASE  alter_table;
CREATE TABLE test (
    f0 BIGINT CODEC(NULL),
    TAGS(t0)
);
ALTER TABLE test DROP COLUMN f0;
ALTER TABLE test DROP COLUMN t0;
ALTER TABLE test DROP COLUMN time;
ALTER TABLE test ADD FIELD time BIGINT;

ALTER TABLE test ADD TAG t1;
DESCRIBE TABLE test;

ALTER TABLE test ADD FIELD f1 BIGINT CODEC(NULL);
DESCRIBE TABLE test;


