--#DATABASE=alter_table
--#SLEEP=0
DROP DATABASE IF EXISTS alter_table;
CREATE DATABASE alter_table WITH TTL '100000d';
CREATE TABLE test (
    f0 BIGINT CODEC(NULL),
    TAGS(t0)
);
ALTER TABLE test DROP f0;
ALTER TABLE test DROP t0;
ALTER TABLE test DROP time;
ALTER TABLE test ADD FIELD time BIGINT;
ALTER TABLE test ADD TAG t0;
ALTER TABLE test ADD FIELD f0 DOUBLE CODEC(DEFAULT);

ALTER TABLE test ADD TAG t1;
DESCRIBE TABLE test;
INSERT INTO test (TIME, t0, t1, f0) VALUES (1, '2', '3', 4), (5, '6', '7', 8);
SELECT * FROM test;

ALTER TABLE test ADD FIELD f1 BIGINT CODEC(NULL);
DESCRIBE TABLE test;
INSERT INTO test (TIME, t0, t1, f0, f1) VALUES (9, '10', '11', 12, 13), (14, '15', '16', 17, 18);
SELECT * FROM test;

ALTER TABLE test DROP f0;
ALTER TABLE test DROP f1;
DESCRIBE TABLE test;
SELECT * FROM test;

ALTER TABLE test ALTER f1 SET CODEC(DEFAULT);
DESCRIBE TABLE test;
SELECT * FROM test;

ALTER TABLE test ALTER t0 SET CODEC(NULL);

ALTER TABLE test ALTER time SET CODEC(NULL);
DESCRIBE TABLE test;



