--#SLEEP=100
ALTER DATABASE test Set TTL '30d';

CREATE DATABASE test WITH TTl '10d' SHARD 5 VNOdE_DURATiON '3d' REPLICA 10 pRECISIOn 'us';

ALTER DATABASE test Set TTL '30d' SHARD 6;

DESCRIBE DATABASE test;

ALTER DATABASE test Set TTL '30d';

DESCRIBE DATABASE test;

ALTER DATABASE test Set SHARD 6;

DESCRIBE DATABASE test;

ALTER DATABASE test Set VNODE_DURATION '100d';

DESCRIBE DATABASE test;

ALTER DATABASE test Set REPLICA 12;

DESCRIBE DATABASE test;

ALTER DATABASE test Set PRECision 'ms';

DESCRIBE DATABASE test;
