@startwbs

title packages layout

* cnosdb
**_ 0
*** cmd/
****< cnos/
****> cnos*ctl/
****> cnos*tool/
*** server/
****_> maintenance/
*****> hinted_handoff/
*****> continuous_query/
*****> time_to_live/
*****> region/
*** cluster/
****> meta/
*****< service.go
*****< store.go
*****< data.go
****> node/
*****< service.go
*****> coordinator/
**_ 1
***> parser/
****< ast.go
***> query/
****< executor.go
****< iterator.go
*** db/
****> index/
****> shard/
*****> index/
*****> tsm1/
*** plugin/
****> prometheus/
****> graphite/
****> udp/
****> opentsdb/
*** internal/
****> logger/
*** util/
****> meta/
*****< meta.go
@endwbs
