name: Prepare Rust Builder
description: 'Prepare Rust Build Environment'
runs:
  using: "composite"
  steps:
    - name: clean pkg
      shell: bash
      run: |
        bash ./.github/tools/free_disk_space.sh
    - name: Install Build Dependencies
      shell: bash
      run: |
        TARGETPLATFORM="linux/amd64" bash ./.github/tools/install_dependencies.sh
    - name: Disable incremental compilation
      # Disable incremental compilation
      shell: bash
      run: echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - uses: rui314/setup-mold@v1

    - name: Fixup git permissions
      # https://github.com/actions/checkout/issues/766
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Enable backtraces
      shell: bash
      run: echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
