// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `gogo.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

/// Extension fields
pub mod exts {

    pub const goproto_enum_prefix: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(62001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_enum_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(62021, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const enum_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(62022, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const enum_customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(62023, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const enumdecl: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(62024, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const enumvalue_customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(66001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const goproto_getters_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_enum_prefix_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63002, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63003, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const verbose_equal_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63004, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const face_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63005, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const gostring_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63006, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const populate_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63007, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63008, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const onlyone_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63009, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const equal_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63013, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const description_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63014, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const testgen_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63015, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const benchgen_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63016, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63017, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const unmarshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63018, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const stable_marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63019, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const sizer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63020, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_enum_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63021, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const enum_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63022, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const unsafe_marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63023, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const unsafe_unmarshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63024, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_extensions_map_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63025, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_unrecognized_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63026, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const gogoproto_import: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63027, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const protosizer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63028, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const compare_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63029, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const typedecl_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63030, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const enumdecl_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63031, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_registration: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63032, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const messagename_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63033, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_sizecache_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63034, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_unkeyed_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(63035, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_getters: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64003, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const verbose_equal: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64004, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const face: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64005, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const gostring: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64006, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const populate: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64007, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(67008, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const onlyone: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64009, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const equal: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64013, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64014, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const testgen: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64015, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const benchgen: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64016, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64017, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const unmarshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64018, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const stable_marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64019, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const sizer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64020, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const unsafe_marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64023, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const unsafe_unmarshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64024, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_extensions_map: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64025, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_unrecognized: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64026, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const protosizer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64028, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const compare: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64029, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const typedecl: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64030, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const messagename: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64033, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_sizecache: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64034, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const goproto_unkeyed: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(64035, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const nullable: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(65001, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const embed: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(65002, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const customtype: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65003, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65004, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const jsontag: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65005, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const moretags: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65006, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const casttype: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65007, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const castkey: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65008, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const castvalue: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::std::string::String> = ::protobuf::ext::ExtFieldOptional::new(65009, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_STRING);

    pub const stdtime: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(65010, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const stdduration: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(65011, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);

    pub const wktpointer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, bool> = ::protobuf::ext::ExtFieldOptional::new(65012, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_BOOL);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\ngogo.proto\x12\tgogoproto\x1a\x20google/protobuf/descriptor.proto:N\
    \n\x13goproto_enum_prefix\x18\xb1\xe4\x03\x20\x01(\x08\x12\x1c.google.pr\
    otobuf.EnumOptionsR\x11goprotoEnumPrefix:R\n\x15goproto_enum_stringer\
    \x18\xc5\xe4\x03\x20\x01(\x08\x12\x1c.google.protobuf.EnumOptionsR\x13go\
    protoEnumStringer:C\n\renum_stringer\x18\xc6\xe4\x03\x20\x01(\x08\x12\
    \x1c.google.protobuf.EnumOptionsR\x0cenumStringer:G\n\x0fenum_customname\
    \x18\xc7\xe4\x03\x20\x01(\t\x12\x1c.google.protobuf.EnumOptionsR\x0eenum\
    Customname::\n\x08enumdecl\x18\xc8\xe4\x03\x20\x01(\x08\x12\x1c.google.p\
    rotobuf.EnumOptionsR\x08enumdecl:V\n\x14enumvalue_customname\x18\xd1\x83\
    \x04\x20\x01(\t\x12!.google.protobuf.EnumValueOptionsR\x13enumvalueCusto\
    mname:N\n\x13goproto_getters_all\x18\x99\xec\x03\x20\x01(\x08\x12\x1c.go\
    ogle.protobuf.FileOptionsR\x11goprotoGettersAll:U\n\x17goproto_enum_pref\
    ix_all\x18\x9a\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\
    \x14goprotoEnumPrefixAll:P\n\x14goproto_stringer_all\x18\x9b\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x12goprotoStringerAll:J\n\
    \x11verbose_equal_all\x18\x9c\xec\x03\x20\x01(\x08\x12\x1c.google.protob\
    uf.FileOptionsR\x0fverboseEqualAll:9\n\x08face_all\x18\x9d\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x07faceAll:A\n\x0cgostrin\
    g_all\x18\x9e\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\
    \x0bgostringAll:A\n\x0cpopulate_all\x18\x9f\xec\x03\x20\x01(\x08\x12\x1c\
    .google.protobuf.FileOptionsR\x0bpopulateAll:A\n\x0cstringer_all\x18\xa0\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0bstringerAl\
    l:?\n\x0bonlyone_all\x18\xa1\xec\x03\x20\x01(\x08\x12\x1c.google.protobu\
    f.FileOptionsR\nonlyoneAll:;\n\tequal_all\x18\xa5\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x08equalAll:G\n\x0fdescription_all\
    \x18\xa6\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0ede\
    scriptionAll:?\n\x0btestgen_all\x18\xa7\xec\x03\x20\x01(\x08\x12\x1c.goo\
    gle.protobuf.FileOptionsR\ntestgenAll:A\n\x0cbenchgen_all\x18\xa8\xec\
    \x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0bbenchgenAll:C\
    \n\rmarshaler_all\x18\xa9\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.F\
    ileOptionsR\x0cmarshalerAll:G\n\x0funmarshaler_all\x18\xaa\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0eunmarshalerAll:P\n\x14\
    stable_marshaler_all\x18\xab\xec\x03\x20\x01(\x08\x12\x1c.google.protobu\
    f.FileOptionsR\x12stableMarshalerAll:;\n\tsizer_all\x18\xac\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x08sizerAll:Y\n\x19goprot\
    o_enum_stringer_all\x18\xad\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf\
    .FileOptionsR\x16goprotoEnumStringerAll:J\n\x11enum_stringer_all\x18\xae\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0fenumString\
    erAll:P\n\x14unsafe_marshaler_all\x18\xaf\xec\x03\x20\x01(\x08\x12\x1c.g\
    oogle.protobuf.FileOptionsR\x12unsafeMarshalerAll:T\n\x16unsafe_unmarsha\
    ler_all\x18\xb0\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptions\
    R\x14unsafeUnmarshalerAll:[\n\x1agoproto_extensions_map_all\x18\xb1\xec\
    \x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x17goprotoExtensi\
    onsMapAll:X\n\x18goproto_unrecognized_all\x18\xb2\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x16goprotoUnrecognizedAll:I\n\x10g\
    ogoproto_import\x18\xb3\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.Fil\
    eOptionsR\x0fgogoprotoImport:E\n\x0eprotosizer_all\x18\xb4\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\rprotosizerAll:?\n\x0bcom\
    pare_all\x18\xb5\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOption\
    sR\ncompareAll:A\n\x0ctypedecl_all\x18\xb6\xec\x03\x20\x01(\x08\x12\x1c.\
    google.protobuf.FileOptionsR\x0btypedeclAll:A\n\x0cenumdecl_all\x18\xb7\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0benumdeclAl\
    l:Q\n\x14goproto_registration\x18\xb8\xec\x03\x20\x01(\x08\x12\x1c.googl\
    e.protobuf.FileOptionsR\x13goprotoRegistration:G\n\x0fmessagename_all\
    \x18\xb9\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0eme\
    ssagenameAll:R\n\x15goproto_sizecache_all\x18\xba\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x13goprotoSizecacheAll:N\n\x13gopr\
    oto_unkeyed_all\x18\xbb\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.Fil\
    eOptionsR\x11goprotoUnkeyedAll:J\n\x0fgoproto_getters\x18\x81\xf4\x03\
    \x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0egoprotoGetters:\
    L\n\x10goproto_stringer\x18\x83\xf4\x03\x20\x01(\x08\x12\x1f.google.prot\
    obuf.MessageOptionsR\x0fgoprotoStringer:F\n\rverbose_equal\x18\x84\xf4\
    \x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0cverboseEqua\
    l:5\n\x04face\x18\x85\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.Messa\
    geOptionsR\x04face:=\n\x08gostring\x18\x86\xf4\x03\x20\x01(\x08\x12\x1f.\
    google.protobuf.MessageOptionsR\x08gostring:=\n\x08populate\x18\x87\xf4\
    \x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x08populate:=\
    \n\x08stringer\x18\xc0\x8b\x04\x20\x01(\x08\x12\x1f.google.protobuf.Mess\
    ageOptionsR\x08stringer:;\n\x07onlyone\x18\x89\xf4\x03\x20\x01(\x08\x12\
    \x1f.google.protobuf.MessageOptionsR\x07onlyone:7\n\x05equal\x18\x8d\xf4\
    \x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x05equal:C\n\
    \x0bdescription\x18\x8e\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.Mes\
    sageOptionsR\x0bdescription:;\n\x07testgen\x18\x8f\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x07testgen:=\n\x08benchgen\x18\
    \x90\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x08ben\
    chgen:?\n\tmarshaler\x18\x91\xf4\x03\x20\x01(\x08\x12\x1f.google.protobu\
    f.MessageOptionsR\tmarshaler:C\n\x0bunmarshaler\x18\x92\xf4\x03\x20\x01(\
    \x08\x12\x1f.google.protobuf.MessageOptionsR\x0bunmarshaler:L\n\x10stabl\
    e_marshaler\x18\x93\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.Message\
    OptionsR\x0fstableMarshaler:7\n\x05sizer\x18\x94\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x05sizer:L\n\x10unsafe_marshale\
    r\x18\x97\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\
    \x0funsafeMarshaler:P\n\x12unsafe_unmarshaler\x18\x98\xf4\x03\x20\x01(\
    \x08\x12\x1f.google.protobuf.MessageOptionsR\x11unsafeUnmarshaler:W\n\
    \x16goproto_extensions_map\x18\x99\xf4\x03\x20\x01(\x08\x12\x1f.google.p\
    rotobuf.MessageOptionsR\x14goprotoExtensionsMap:T\n\x14goproto_unrecogni\
    zed\x18\x9a\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\
    \x13goprotoUnrecognized:A\n\nprotosizer\x18\x9c\xf4\x03\x20\x01(\x08\x12\
    \x1f.google.protobuf.MessageOptionsR\nprotosizer:;\n\x07compare\x18\x9d\
    \xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x07compare\
    :=\n\x08typedecl\x18\x9e\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.Me\
    ssageOptionsR\x08typedecl:C\n\x0bmessagename\x18\xa1\xf4\x03\x20\x01(\
    \x08\x12\x1f.google.protobuf.MessageOptionsR\x0bmessagename:N\n\x11gopro\
    to_sizecache\x18\xa2\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.Messag\
    eOptionsR\x10goprotoSizecache:J\n\x0fgoproto_unkeyed\x18\xa3\xf4\x03\x20\
    \x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0egoprotoUnkeyed:;\n\
    \x08nullable\x18\xe9\xfb\x03\x20\x01(\x08\x12\x1d.google.protobuf.FieldO\
    ptionsR\x08nullable:5\n\x05embed\x18\xea\xfb\x03\x20\x01(\x08\x12\x1d.go\
    ogle.protobuf.FieldOptionsR\x05embed:?\n\ncustomtype\x18\xeb\xfb\x03\x20\
    \x01(\t\x12\x1d.google.protobuf.FieldOptionsR\ncustomtype:?\n\ncustomnam\
    e\x18\xec\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\ncust\
    omname:9\n\x07jsontag\x18\xed\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf\
    .FieldOptionsR\x07jsontag:;\n\x08moretags\x18\xee\xfb\x03\x20\x01(\t\x12\
    \x1d.google.protobuf.FieldOptionsR\x08moretags:;\n\x08casttype\x18\xef\
    \xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x08casttype:9\
    \n\x07castkey\x18\xf0\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOp\
    tionsR\x07castkey:=\n\tcastvalue\x18\xf1\xfb\x03\x20\x01(\t\x12\x1d.goog\
    le.protobuf.FieldOptionsR\tcastvalue:9\n\x07stdtime\x18\xf2\xfb\x03\x20\
    \x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\x07stdtime:A\n\x0bstddur\
    ation\x18\xf3\xfb\x03\x20\x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\
    \x0bstdduration:?\n\nwktpointer\x18\xf4\xfb\x03\x20\x01(\x08\x12\x1d.goo\
    gle.protobuf.FieldOptionsR\nwktpointerBE\n\x13com.google.protobufB\nGoGo\
    ProtosZ\"github.com/gogo/protobuf/gogoprotoJ\xf16\n\x07\x12\x05\x1c\0\
    \x8f\x01\x01\n\xfc\n\n\x01\x0c\x12\x03\x1c\0\x122\xf1\n\x20Protocol\x20B\
    uffers\x20for\x20Go\x20with\x20Gadgets\n\n\x20Copyright\x20(c)\x202013,\
    \x20The\x20GoGo\x20Authors.\x20All\x20rights\x20reserved.\n\x20http://gi\
    thub.com/gogo/protobuf\n\n\x20Redistribution\x20and\x20use\x20in\x20sour\
    ce\x20and\x20binary\x20forms,\x20with\x20or\x20without\n\x20modification\
    ,\x20are\x20permitted\x20provided\x20that\x20the\x20following\x20conditi\
    ons\x20are\n\x20met:\n\n\x20\x20\x20\x20\x20*\x20Redistributions\x20of\
    \x20source\x20code\x20must\x20retain\x20the\x20above\x20copyright\n\x20n\
    otice,\x20this\x20list\x20of\x20conditions\x20and\x20the\x20following\
    \x20disclaimer.\n\x20\x20\x20\x20\x20*\x20Redistributions\x20in\x20binar\
    y\x20form\x20must\x20reproduce\x20the\x20above\n\x20copyright\x20notice,\
    \x20this\x20list\x20of\x20conditions\x20and\x20the\x20following\x20discl\
    aimer\n\x20in\x20the\x20documentation\x20and/or\x20other\x20materials\
    \x20provided\x20with\x20the\n\x20distribution.\n\n\x20THIS\x20SOFTWARE\
    \x20IS\x20PROVIDED\x20BY\x20THE\x20COPYRIGHT\x20HOLDERS\x20AND\x20CONTRI\
    BUTORS\n\x20\"AS\x20IS\"\x20AND\x20ANY\x20EXPRESS\x20OR\x20IMPLIED\x20WA\
    RRANTIES,\x20INCLUDING,\x20BUT\x20NOT\n\x20LIMITED\x20TO,\x20THE\x20IMPL\
    IED\x20WARRANTIES\x20OF\x20MERCHANTABILITY\x20AND\x20FITNESS\x20FOR\n\
    \x20A\x20PARTICULAR\x20PURPOSE\x20ARE\x20DISCLAIMED.\x20IN\x20NO\x20EVEN\
    T\x20SHALL\x20THE\x20COPYRIGHT\n\x20OWNER\x20OR\x20CONTRIBUTORS\x20BE\
    \x20LIABLE\x20FOR\x20ANY\x20DIRECT,\x20INDIRECT,\x20INCIDENTAL,\n\x20SPE\
    CIAL,\x20EXEMPLARY,\x20OR\x20CONSEQUENTIAL\x20DAMAGES\x20(INCLUDING,\x20\
    BUT\x20NOT\n\x20LIMITED\x20TO,\x20PROCUREMENT\x20OF\x20SUBSTITUTE\x20GOO\
    DS\x20OR\x20SERVICES;\x20LOSS\x20OF\x20USE,\n\x20DATA,\x20OR\x20PROFITS;\
    \x20OR\x20BUSINESS\x20INTERRUPTION)\x20HOWEVER\x20CAUSED\x20AND\x20ON\
    \x20ANY\n\x20THEORY\x20OF\x20LIABILITY,\x20WHETHER\x20IN\x20CONTRACT,\
    \x20STRICT\x20LIABILITY,\x20OR\x20TORT\n\x20(INCLUDING\x20NEGLIGENCE\x20\
    OR\x20OTHERWISE)\x20ARISING\x20IN\x20ANY\x20WAY\x20OUT\x20OF\x20THE\x20U\
    SE\n\x20OF\x20THIS\x20SOFTWARE,\x20EVEN\x20IF\x20ADVISED\x20OF\x20THE\
    \x20POSSIBILITY\x20OF\x20SUCH\x20DAMAGE.\n\n\x08\n\x01\x02\x12\x03\x1d\0\
    \x12\n\t\n\x02\x03\0\x12\x03\x1f\0*\n\x08\n\x01\x08\x12\x03!\0,\n\t\n\
    \x02\x08\x01\x12\x03!\0,\n\x08\n\x01\x08\x12\x03\"\0+\n\t\n\x02\x08\x08\
    \x12\x03\"\0+\n\x08\n\x01\x08\x12\x03#\09\n\t\n\x02\x08\x0b\x12\x03#\09\
    \n\t\n\x01\x07\x12\x04%\0+\x01\n\t\n\x02\x07\0\x12\x03&\x082\n\n\n\x03\
    \x07\0\x02\x12\x03%\x07\"\n\n\n\x03\x07\0\x04\x12\x03&\x08\x10\n\n\n\x03\
    \x07\0\x05\x12\x03&\x11\x15\n\n\n\x03\x07\0\x01\x12\x03&\x16)\n\n\n\x03\
    \x07\0\x03\x12\x03&,1\n\t\n\x02\x07\x01\x12\x03'\x084\n\n\n\x03\x07\x01\
    \x02\x12\x03%\x07\"\n\n\n\x03\x07\x01\x04\x12\x03'\x08\x10\n\n\n\x03\x07\
    \x01\x05\x12\x03'\x11\x15\n\n\n\x03\x07\x01\x01\x12\x03'\x16+\n\n\n\x03\
    \x07\x01\x03\x12\x03'.3\n\t\n\x02\x07\x02\x12\x03(\x08,\n\n\n\x03\x07\
    \x02\x02\x12\x03%\x07\"\n\n\n\x03\x07\x02\x04\x12\x03(\x08\x10\n\n\n\x03\
    \x07\x02\x05\x12\x03(\x11\x15\n\n\n\x03\x07\x02\x01\x12\x03(\x16#\n\n\n\
    \x03\x07\x02\x03\x12\x03(&+\n\t\n\x02\x07\x03\x12\x03)\x080\n\n\n\x03\
    \x07\x03\x02\x12\x03%\x07\"\n\n\n\x03\x07\x03\x04\x12\x03)\x08\x10\n\n\n\
    \x03\x07\x03\x05\x12\x03)\x11\x17\n\n\n\x03\x07\x03\x01\x12\x03)\x18'\n\
    \n\n\x03\x07\x03\x03\x12\x03)*/\n\t\n\x02\x07\x04\x12\x03*\x08'\n\n\n\
    \x03\x07\x04\x02\x12\x03%\x07\"\n\n\n\x03\x07\x04\x04\x12\x03*\x08\x10\n\
    \n\n\x03\x07\x04\x05\x12\x03*\x11\x15\n\n\n\x03\x07\x04\x01\x12\x03*\x16\
    \x1e\n\n\n\x03\x07\x04\x03\x12\x03*!&\n\t\n\x01\x07\x12\x04-\0/\x01\n\t\
    \n\x02\x07\x05\x12\x03.\x085\n\n\n\x03\x07\x05\x02\x12\x03-\x07'\n\n\n\
    \x03\x07\x05\x04\x12\x03.\x08\x10\n\n\n\x03\x07\x05\x05\x12\x03.\x11\x17\
    \n\n\n\x03\x07\x05\x01\x12\x03.\x18,\n\n\n\x03\x07\x05\x03\x12\x03./4\n\
    \t\n\x01\x07\x12\x041\0Y\x01\n\t\n\x02\x07\x06\x12\x032\x082\n\n\n\x03\
    \x07\x06\x02\x12\x031\x07\"\n\n\n\x03\x07\x06\x04\x12\x032\x08\x10\n\n\n\
    \x03\x07\x06\x05\x12\x032\x11\x15\n\n\n\x03\x07\x06\x01\x12\x032\x16)\n\
    \n\n\x03\x07\x06\x03\x12\x032,1\n\t\n\x02\x07\x07\x12\x033\x086\n\n\n\
    \x03\x07\x07\x02\x12\x031\x07\"\n\n\n\x03\x07\x07\x04\x12\x033\x08\x10\n\
    \n\n\x03\x07\x07\x05\x12\x033\x11\x15\n\n\n\x03\x07\x07\x01\x12\x033\x16\
    -\n\n\n\x03\x07\x07\x03\x12\x03305\n\t\n\x02\x07\x08\x12\x034\x083\n\n\n\
    \x03\x07\x08\x02\x12\x031\x07\"\n\n\n\x03\x07\x08\x04\x12\x034\x08\x10\n\
    \n\n\x03\x07\x08\x05\x12\x034\x11\x15\n\n\n\x03\x07\x08\x01\x12\x034\x16\
    *\n\n\n\x03\x07\x08\x03\x12\x034-2\n\t\n\x02\x07\t\x12\x035\x080\n\n\n\
    \x03\x07\t\x02\x12\x031\x07\"\n\n\n\x03\x07\t\x04\x12\x035\x08\x10\n\n\n\
    \x03\x07\t\x05\x12\x035\x11\x15\n\n\n\x03\x07\t\x01\x12\x035\x16'\n\n\n\
    \x03\x07\t\x03\x12\x035*/\n\t\n\x02\x07\n\x12\x036\x08'\n\n\n\x03\x07\n\
    \x02\x12\x031\x07\"\n\n\n\x03\x07\n\x04\x12\x036\x08\x10\n\n\n\x03\x07\n\
    \x05\x12\x036\x11\x15\n\n\n\x03\x07\n\x01\x12\x036\x16\x1e\n\n\n\x03\x07\
    \n\x03\x12\x036!&\n\t\n\x02\x07\x0b\x12\x037\x08+\n\n\n\x03\x07\x0b\x02\
    \x12\x031\x07\"\n\n\n\x03\x07\x0b\x04\x12\x037\x08\x10\n\n\n\x03\x07\x0b\
    \x05\x12\x037\x11\x15\n\n\n\x03\x07\x0b\x01\x12\x037\x16\"\n\n\n\x03\x07\
    \x0b\x03\x12\x037%*\n\t\n\x02\x07\x0c\x12\x038\x08+\n\n\n\x03\x07\x0c\
    \x02\x12\x031\x07\"\n\n\n\x03\x07\x0c\x04\x12\x038\x08\x10\n\n\n\x03\x07\
    \x0c\x05\x12\x038\x11\x15\n\n\n\x03\x07\x0c\x01\x12\x038\x16\"\n\n\n\x03\
    \x07\x0c\x03\x12\x038%*\n\t\n\x02\x07\r\x12\x039\x08+\n\n\n\x03\x07\r\
    \x02\x12\x031\x07\"\n\n\n\x03\x07\r\x04\x12\x039\x08\x10\n\n\n\x03\x07\r\
    \x05\x12\x039\x11\x15\n\n\n\x03\x07\r\x01\x12\x039\x16\"\n\n\n\x03\x07\r\
    \x03\x12\x039%*\n\t\n\x02\x07\x0e\x12\x03:\x08*\n\n\n\x03\x07\x0e\x02\
    \x12\x031\x07\"\n\n\n\x03\x07\x0e\x04\x12\x03:\x08\x10\n\n\n\x03\x07\x0e\
    \x05\x12\x03:\x11\x15\n\n\n\x03\x07\x0e\x01\x12\x03:\x16!\n\n\n\x03\x07\
    \x0e\x03\x12\x03:$)\n\t\n\x02\x07\x0f\x12\x03<\x08(\n\n\n\x03\x07\x0f\
    \x02\x12\x031\x07\"\n\n\n\x03\x07\x0f\x04\x12\x03<\x08\x10\n\n\n\x03\x07\
    \x0f\x05\x12\x03<\x11\x15\n\n\n\x03\x07\x0f\x01\x12\x03<\x16\x1f\n\n\n\
    \x03\x07\x0f\x03\x12\x03<\"'\n\t\n\x02\x07\x10\x12\x03=\x08.\n\n\n\x03\
    \x07\x10\x02\x12\x031\x07\"\n\n\n\x03\x07\x10\x04\x12\x03=\x08\x10\n\n\n\
    \x03\x07\x10\x05\x12\x03=\x11\x15\n\n\n\x03\x07\x10\x01\x12\x03=\x16%\n\
    \n\n\x03\x07\x10\x03\x12\x03=(-\n\t\n\x02\x07\x11\x12\x03>\x08*\n\n\n\
    \x03\x07\x11\x02\x12\x031\x07\"\n\n\n\x03\x07\x11\x04\x12\x03>\x08\x10\n\
    \n\n\x03\x07\x11\x05\x12\x03>\x11\x15\n\n\n\x03\x07\x11\x01\x12\x03>\x16\
    !\n\n\n\x03\x07\x11\x03\x12\x03>$)\n\t\n\x02\x07\x12\x12\x03?\x08+\n\n\n\
    \x03\x07\x12\x02\x12\x031\x07\"\n\n\n\x03\x07\x12\x04\x12\x03?\x08\x10\n\
    \n\n\x03\x07\x12\x05\x12\x03?\x11\x15\n\n\n\x03\x07\x12\x01\x12\x03?\x16\
    \"\n\n\n\x03\x07\x12\x03\x12\x03?%*\n\t\n\x02\x07\x13\x12\x03@\x08,\n\n\
    \n\x03\x07\x13\x02\x12\x031\x07\"\n\n\n\x03\x07\x13\x04\x12\x03@\x08\x10\
    \n\n\n\x03\x07\x13\x05\x12\x03@\x11\x15\n\n\n\x03\x07\x13\x01\x12\x03@\
    \x16#\n\n\n\x03\x07\x13\x03\x12\x03@&+\n\t\n\x02\x07\x14\x12\x03A\x08.\n\
    \n\n\x03\x07\x14\x02\x12\x031\x07\"\n\n\n\x03\x07\x14\x04\x12\x03A\x08\
    \x10\n\n\n\x03\x07\x14\x05\x12\x03A\x11\x15\n\n\n\x03\x07\x14\x01\x12\
    \x03A\x16%\n\n\n\x03\x07\x14\x03\x12\x03A(-\n\t\n\x02\x07\x15\x12\x03B\
    \x083\n\n\n\x03\x07\x15\x02\x12\x031\x07\"\n\n\n\x03\x07\x15\x04\x12\x03\
    B\x08\x10\n\n\n\x03\x07\x15\x05\x12\x03B\x11\x15\n\n\n\x03\x07\x15\x01\
    \x12\x03B\x16*\n\n\n\x03\x07\x15\x03\x12\x03B-2\n\t\n\x02\x07\x16\x12\
    \x03D\x08(\n\n\n\x03\x07\x16\x02\x12\x031\x07\"\n\n\n\x03\x07\x16\x04\
    \x12\x03D\x08\x10\n\n\n\x03\x07\x16\x05\x12\x03D\x11\x15\n\n\n\x03\x07\
    \x16\x01\x12\x03D\x16\x1f\n\n\n\x03\x07\x16\x03\x12\x03D\"'\n\t\n\x02\
    \x07\x17\x12\x03F\x088\n\n\n\x03\x07\x17\x02\x12\x031\x07\"\n\n\n\x03\
    \x07\x17\x04\x12\x03F\x08\x10\n\n\n\x03\x07\x17\x05\x12\x03F\x11\x15\n\n\
    \n\x03\x07\x17\x01\x12\x03F\x16/\n\n\n\x03\x07\x17\x03\x12\x03F27\n\t\n\
    \x02\x07\x18\x12\x03G\x080\n\n\n\x03\x07\x18\x02\x12\x031\x07\"\n\n\n\
    \x03\x07\x18\x04\x12\x03G\x08\x10\n\n\n\x03\x07\x18\x05\x12\x03G\x11\x15\
    \n\n\n\x03\x07\x18\x01\x12\x03G\x16'\n\n\n\x03\x07\x18\x03\x12\x03G*/\n\
    \t\n\x02\x07\x19\x12\x03I\x083\n\n\n\x03\x07\x19\x02\x12\x031\x07\"\n\n\
    \n\x03\x07\x19\x04\x12\x03I\x08\x10\n\n\n\x03\x07\x19\x05\x12\x03I\x11\
    \x15\n\n\n\x03\x07\x19\x01\x12\x03I\x16*\n\n\n\x03\x07\x19\x03\x12\x03I-\
    2\n\t\n\x02\x07\x1a\x12\x03J\x085\n\n\n\x03\x07\x1a\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x1a\x04\x12\x03J\x08\x10\n\n\n\x03\x07\x1a\x05\x12\x03J\x11\
    \x15\n\n\n\x03\x07\x1a\x01\x12\x03J\x16,\n\n\n\x03\x07\x1a\x03\x12\x03J/\
    4\n\t\n\x02\x07\x1b\x12\x03L\x089\n\n\n\x03\x07\x1b\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x1b\x04\x12\x03L\x08\x10\n\n\n\x03\x07\x1b\x05\x12\x03L\x11\
    \x15\n\n\n\x03\x07\x1b\x01\x12\x03L\x160\n\n\n\x03\x07\x1b\x03\x12\x03L3\
    8\n\t\n\x02\x07\x1c\x12\x03M\x087\n\n\n\x03\x07\x1c\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x1c\x04\x12\x03M\x08\x10\n\n\n\x03\x07\x1c\x05\x12\x03M\x11\
    \x15\n\n\n\x03\x07\x1c\x01\x12\x03M\x16.\n\n\n\x03\x07\x1c\x03\x12\x03M1\
    6\n\t\n\x02\x07\x1d\x12\x03N\x08/\n\n\n\x03\x07\x1d\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x1d\x04\x12\x03N\x08\x10\n\n\n\x03\x07\x1d\x05\x12\x03N\x11\
    \x15\n\n\n\x03\x07\x1d\x01\x12\x03N\x16&\n\n\n\x03\x07\x1d\x03\x12\x03N)\
    .\n\t\n\x02\x07\x1e\x12\x03O\x08-\n\n\n\x03\x07\x1e\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x1e\x04\x12\x03O\x08\x10\n\n\n\x03\x07\x1e\x05\x12\x03O\x11\
    \x15\n\n\n\x03\x07\x1e\x01\x12\x03O\x16$\n\n\n\x03\x07\x1e\x03\x12\x03O'\
    ,\n\t\n\x02\x07\x1f\x12\x03P\x08*\n\n\n\x03\x07\x1f\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x1f\x04\x12\x03P\x08\x10\n\n\n\x03\x07\x1f\x05\x12\x03P\x11\
    \x15\n\n\n\x03\x07\x1f\x01\x12\x03P\x16!\n\n\n\x03\x07\x1f\x03\x12\x03P$\
    )\n\t\n\x02\x07\x20\x12\x03Q\x04'\n\n\n\x03\x07\x20\x02\x12\x031\x07\"\n\
    \n\n\x03\x07\x20\x04\x12\x03Q\x04\x0c\n\n\n\x03\x07\x20\x05\x12\x03Q\r\
    \x11\n\n\n\x03\x07\x20\x01\x12\x03Q\x12\x1e\n\n\n\x03\x07\x20\x03\x12\
    \x03Q!&\n\t\n\x02\x07!\x12\x03R\x04'\n\n\n\x03\x07!\x02\x12\x031\x07\"\n\
    \n\n\x03\x07!\x04\x12\x03R\x04\x0c\n\n\n\x03\x07!\x05\x12\x03R\r\x11\n\n\
    \n\x03\x07!\x01\x12\x03R\x12\x1e\n\n\n\x03\x07!\x03\x12\x03R!&\n\t\n\x02\
    \x07\"\x12\x03T\x083\n\n\n\x03\x07\"\x02\x12\x031\x07\"\n\n\n\x03\x07\"\
    \x04\x12\x03T\x08\x10\n\n\n\x03\x07\"\x05\x12\x03T\x11\x15\n\n\n\x03\x07\
    \"\x01\x12\x03T\x16*\n\n\n\x03\x07\"\x03\x12\x03T-2\n\t\n\x02\x07#\x12\
    \x03U\x08.\n\n\n\x03\x07#\x02\x12\x031\x07\"\n\n\n\x03\x07#\x04\x12\x03U\
    \x08\x10\n\n\n\x03\x07#\x05\x12\x03U\x11\x15\n\n\n\x03\x07#\x01\x12\x03U\
    \x16%\n\n\n\x03\x07#\x03\x12\x03U(-\n\t\n\x02\x07$\x12\x03W\x084\n\n\n\
    \x03\x07$\x02\x12\x031\x07\"\n\n\n\x03\x07$\x04\x12\x03W\x08\x10\n\n\n\
    \x03\x07$\x05\x12\x03W\x11\x15\n\n\n\x03\x07$\x01\x12\x03W\x16+\n\n\n\
    \x03\x07$\x03\x12\x03W.3\n\t\n\x02\x07%\x12\x03X\x082\n\n\n\x03\x07%\x02\
    \x12\x031\x07\"\n\n\n\x03\x07%\x04\x12\x03X\x08\x10\n\n\n\x03\x07%\x05\
    \x12\x03X\x11\x15\n\n\n\x03\x07%\x01\x12\x03X\x16)\n\n\n\x03\x07%\x03\
    \x12\x03X,1\n\t\n\x01\x07\x12\x04[\0~\x01\n\t\n\x02\x07&\x12\x03\\\x08.\
    \n\n\n\x03\x07&\x02\x12\x03[\x07%\n\n\n\x03\x07&\x04\x12\x03\\\x08\x10\n\
    \n\n\x03\x07&\x05\x12\x03\\\x11\x15\n\n\n\x03\x07&\x01\x12\x03\\\x16%\n\
    \n\n\x03\x07&\x03\x12\x03\\(-\n\t\n\x02\x07'\x12\x03]\x08/\n\n\n\x03\x07\
    '\x02\x12\x03[\x07%\n\n\n\x03\x07'\x04\x12\x03]\x08\x10\n\n\n\x03\x07'\
    \x05\x12\x03]\x11\x15\n\n\n\x03\x07'\x01\x12\x03]\x16&\n\n\n\x03\x07'\
    \x03\x12\x03]).\n\t\n\x02\x07(\x12\x03^\x08,\n\n\n\x03\x07(\x02\x12\x03[\
    \x07%\n\n\n\x03\x07(\x04\x12\x03^\x08\x10\n\n\n\x03\x07(\x05\x12\x03^\
    \x11\x15\n\n\n\x03\x07(\x01\x12\x03^\x16#\n\n\n\x03\x07(\x03\x12\x03^&+\
    \n\t\n\x02\x07)\x12\x03_\x08#\n\n\n\x03\x07)\x02\x12\x03[\x07%\n\n\n\x03\
    \x07)\x04\x12\x03_\x08\x10\n\n\n\x03\x07)\x05\x12\x03_\x11\x15\n\n\n\x03\
    \x07)\x01\x12\x03_\x16\x1a\n\n\n\x03\x07)\x03\x12\x03_\x1d\"\n\t\n\x02\
    \x07*\x12\x03`\x08'\n\n\n\x03\x07*\x02\x12\x03[\x07%\n\n\n\x03\x07*\x04\
    \x12\x03`\x08\x10\n\n\n\x03\x07*\x05\x12\x03`\x11\x15\n\n\n\x03\x07*\x01\
    \x12\x03`\x16\x1e\n\n\n\x03\x07*\x03\x12\x03`!&\n\t\n\x02\x07+\x12\x03a\
    \x08'\n\n\n\x03\x07+\x02\x12\x03[\x07%\n\n\n\x03\x07+\x04\x12\x03a\x08\
    \x10\n\n\n\x03\x07+\x05\x12\x03a\x11\x15\n\n\n\x03\x07+\x01\x12\x03a\x16\
    \x1e\n\n\n\x03\x07+\x03\x12\x03a!&\n\t\n\x02\x07,\x12\x03b\x08'\n\n\n\
    \x03\x07,\x02\x12\x03[\x07%\n\n\n\x03\x07,\x04\x12\x03b\x08\x10\n\n\n\
    \x03\x07,\x05\x12\x03b\x11\x15\n\n\n\x03\x07,\x01\x12\x03b\x16\x1e\n\n\n\
    \x03\x07,\x03\x12\x03b!&\n\t\n\x02\x07-\x12\x03c\x08&\n\n\n\x03\x07-\x02\
    \x12\x03[\x07%\n\n\n\x03\x07-\x04\x12\x03c\x08\x10\n\n\n\x03\x07-\x05\
    \x12\x03c\x11\x15\n\n\n\x03\x07-\x01\x12\x03c\x16\x1d\n\n\n\x03\x07-\x03\
    \x12\x03c\x20%\n\t\n\x02\x07.\x12\x03e\x08$\n\n\n\x03\x07.\x02\x12\x03[\
    \x07%\n\n\n\x03\x07.\x04\x12\x03e\x08\x10\n\n\n\x03\x07.\x05\x12\x03e\
    \x11\x15\n\n\n\x03\x07.\x01\x12\x03e\x16\x1b\n\n\n\x03\x07.\x03\x12\x03e\
    \x1e#\n\t\n\x02\x07/\x12\x03f\x08*\n\n\n\x03\x07/\x02\x12\x03[\x07%\n\n\
    \n\x03\x07/\x04\x12\x03f\x08\x10\n\n\n\x03\x07/\x05\x12\x03f\x11\x15\n\n\
    \n\x03\x07/\x01\x12\x03f\x16!\n\n\n\x03\x07/\x03\x12\x03f$)\n\t\n\x02\
    \x070\x12\x03g\x08&\n\n\n\x03\x070\x02\x12\x03[\x07%\n\n\n\x03\x070\x04\
    \x12\x03g\x08\x10\n\n\n\x03\x070\x05\x12\x03g\x11\x15\n\n\n\x03\x070\x01\
    \x12\x03g\x16\x1d\n\n\n\x03\x070\x03\x12\x03g\x20%\n\t\n\x02\x071\x12\
    \x03h\x08'\n\n\n\x03\x071\x02\x12\x03[\x07%\n\n\n\x03\x071\x04\x12\x03h\
    \x08\x10\n\n\n\x03\x071\x05\x12\x03h\x11\x15\n\n\n\x03\x071\x01\x12\x03h\
    \x16\x1e\n\n\n\x03\x071\x03\x12\x03h!&\n\t\n\x02\x072\x12\x03i\x08(\n\n\
    \n\x03\x072\x02\x12\x03[\x07%\n\n\n\x03\x072\x04\x12\x03i\x08\x10\n\n\n\
    \x03\x072\x05\x12\x03i\x11\x15\n\n\n\x03\x072\x01\x12\x03i\x16\x1f\n\n\n\
    \x03\x072\x03\x12\x03i\"'\n\t\n\x02\x073\x12\x03j\x08*\n\n\n\x03\x073\
    \x02\x12\x03[\x07%\n\n\n\x03\x073\x04\x12\x03j\x08\x10\n\n\n\x03\x073\
    \x05\x12\x03j\x11\x15\n\n\n\x03\x073\x01\x12\x03j\x16!\n\n\n\x03\x073\
    \x03\x12\x03j$)\n\t\n\x02\x074\x12\x03k\x08/\n\n\n\x03\x074\x02\x12\x03[\
    \x07%\n\n\n\x03\x074\x04\x12\x03k\x08\x10\n\n\n\x03\x074\x05\x12\x03k\
    \x11\x15\n\n\n\x03\x074\x01\x12\x03k\x16&\n\n\n\x03\x074\x03\x12\x03k).\
    \n\t\n\x02\x075\x12\x03m\x08$\n\n\n\x03\x075\x02\x12\x03[\x07%\n\n\n\x03\
    \x075\x04\x12\x03m\x08\x10\n\n\n\x03\x075\x05\x12\x03m\x11\x15\n\n\n\x03\
    \x075\x01\x12\x03m\x16\x1b\n\n\n\x03\x075\x03\x12\x03m\x1e#\n\t\n\x02\
    \x076\x12\x03o\x08/\n\n\n\x03\x076\x02\x12\x03[\x07%\n\n\n\x03\x076\x04\
    \x12\x03o\x08\x10\n\n\n\x03\x076\x05\x12\x03o\x11\x15\n\n\n\x03\x076\x01\
    \x12\x03o\x16&\n\n\n\x03\x076\x03\x12\x03o).\n\t\n\x02\x077\x12\x03p\x08\
    1\n\n\n\x03\x077\x02\x12\x03[\x07%\n\n\n\x03\x077\x04\x12\x03p\x08\x10\n\
    \n\n\x03\x077\x05\x12\x03p\x11\x15\n\n\n\x03\x077\x01\x12\x03p\x16(\n\n\
    \n\x03\x077\x03\x12\x03p+0\n\t\n\x02\x078\x12\x03r\x085\n\n\n\x03\x078\
    \x02\x12\x03[\x07%\n\n\n\x03\x078\x04\x12\x03r\x08\x10\n\n\n\x03\x078\
    \x05\x12\x03r\x11\x15\n\n\n\x03\x078\x01\x12\x03r\x16,\n\n\n\x03\x078\
    \x03\x12\x03r/4\n\t\n\x02\x079\x12\x03s\x083\n\n\n\x03\x079\x02\x12\x03[\
    \x07%\n\n\n\x03\x079\x04\x12\x03s\x08\x10\n\n\n\x03\x079\x05\x12\x03s\
    \x11\x15\n\n\n\x03\x079\x01\x12\x03s\x16*\n\n\n\x03\x079\x03\x12\x03s-2\
    \n\t\n\x02\x07:\x12\x03u\x08)\n\n\n\x03\x07:\x02\x12\x03[\x07%\n\n\n\x03\
    \x07:\x04\x12\x03u\x08\x10\n\n\n\x03\x07:\x05\x12\x03u\x11\x15\n\n\n\x03\
    \x07:\x01\x12\x03u\x16\x20\n\n\n\x03\x07:\x03\x12\x03u#(\n\t\n\x02\x07;\
    \x12\x03v\x08&\n\n\n\x03\x07;\x02\x12\x03[\x07%\n\n\n\x03\x07;\x04\x12\
    \x03v\x08\x10\n\n\n\x03\x07;\x05\x12\x03v\x11\x15\n\n\n\x03\x07;\x01\x12\
    \x03v\x16\x1d\n\n\n\x03\x07;\x03\x12\x03v\x20%\n\t\n\x02\x07<\x12\x03x\
    \x08'\n\n\n\x03\x07<\x02\x12\x03[\x07%\n\n\n\x03\x07<\x04\x12\x03x\x08\
    \x10\n\n\n\x03\x07<\x05\x12\x03x\x11\x15\n\n\n\x03\x07<\x01\x12\x03x\x16\
    \x1e\n\n\n\x03\x07<\x03\x12\x03x!&\n\t\n\x02\x07=\x12\x03z\x08*\n\n\n\
    \x03\x07=\x02\x12\x03[\x07%\n\n\n\x03\x07=\x04\x12\x03z\x08\x10\n\n\n\
    \x03\x07=\x05\x12\x03z\x11\x15\n\n\n\x03\x07=\x01\x12\x03z\x16!\n\n\n\
    \x03\x07=\x03\x12\x03z$)\n\t\n\x02\x07>\x12\x03|\x080\n\n\n\x03\x07>\x02\
    \x12\x03[\x07%\n\n\n\x03\x07>\x04\x12\x03|\x08\x10\n\n\n\x03\x07>\x05\
    \x12\x03|\x11\x15\n\n\n\x03\x07>\x01\x12\x03|\x16'\n\n\n\x03\x07>\x03\
    \x12\x03|*/\n\t\n\x02\x07?\x12\x03}\x08.\n\n\n\x03\x07?\x02\x12\x03[\x07\
    %\n\n\n\x03\x07?\x04\x12\x03}\x08\x10\n\n\n\x03\x07?\x05\x12\x03}\x11\
    \x15\n\n\n\x03\x07?\x01\x12\x03}\x16%\n\n\n\x03\x07?\x03\x12\x03}(-\n\
    \x0b\n\x01\x07\x12\x06\x80\x01\0\x8f\x01\x01\n\n\n\x02\x07@\x12\x04\x81\
    \x01\x08'\n\x0b\n\x03\x07@\x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\x07@\x04\
    \x12\x04\x81\x01\x08\x10\n\x0b\n\x03\x07@\x05\x12\x04\x81\x01\x11\x15\n\
    \x0b\n\x03\x07@\x01\x12\x04\x81\x01\x16\x1e\n\x0b\n\x03\x07@\x03\x12\x04\
    \x81\x01!&\n\n\n\x02\x07A\x12\x04\x82\x01\x08$\n\x0b\n\x03\x07A\x02\x12\
    \x04\x80\x01\x07#\n\x0b\n\x03\x07A\x04\x12\x04\x82\x01\x08\x10\n\x0b\n\
    \x03\x07A\x05\x12\x04\x82\x01\x11\x15\n\x0b\n\x03\x07A\x01\x12\x04\x82\
    \x01\x16\x1b\n\x0b\n\x03\x07A\x03\x12\x04\x82\x01\x1e#\n\n\n\x02\x07B\
    \x12\x04\x83\x01\x08+\n\x0b\n\x03\x07B\x02\x12\x04\x80\x01\x07#\n\x0b\n\
    \x03\x07B\x04\x12\x04\x83\x01\x08\x10\n\x0b\n\x03\x07B\x05\x12\x04\x83\
    \x01\x11\x17\n\x0b\n\x03\x07B\x01\x12\x04\x83\x01\x18\"\n\x0b\n\x03\x07B\
    \x03\x12\x04\x83\x01%*\n\n\n\x02\x07C\x12\x04\x84\x01\x08+\n\x0b\n\x03\
    \x07C\x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\x07C\x04\x12\x04\x84\x01\x08\
    \x10\n\x0b\n\x03\x07C\x05\x12\x04\x84\x01\x11\x17\n\x0b\n\x03\x07C\x01\
    \x12\x04\x84\x01\x18\"\n\x0b\n\x03\x07C\x03\x12\x04\x84\x01%*\n\n\n\x02\
    \x07D\x12\x04\x85\x01\x08(\n\x0b\n\x03\x07D\x02\x12\x04\x80\x01\x07#\n\
    \x0b\n\x03\x07D\x04\x12\x04\x85\x01\x08\x10\n\x0b\n\x03\x07D\x05\x12\x04\
    \x85\x01\x11\x17\n\x0b\n\x03\x07D\x01\x12\x04\x85\x01\x18\x1f\n\x0b\n\
    \x03\x07D\x03\x12\x04\x85\x01\"'\n\n\n\x02\x07E\x12\x04\x86\x01\x08)\n\
    \x0b\n\x03\x07E\x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\x07E\x04\x12\x04\
    \x86\x01\x08\x10\n\x0b\n\x03\x07E\x05\x12\x04\x86\x01\x11\x17\n\x0b\n\
    \x03\x07E\x01\x12\x04\x86\x01\x18\x20\n\x0b\n\x03\x07E\x03\x12\x04\x86\
    \x01#(\n\n\n\x02\x07F\x12\x04\x87\x01\x08)\n\x0b\n\x03\x07F\x02\x12\x04\
    \x80\x01\x07#\n\x0b\n\x03\x07F\x04\x12\x04\x87\x01\x08\x10\n\x0b\n\x03\
    \x07F\x05\x12\x04\x87\x01\x11\x17\n\x0b\n\x03\x07F\x01\x12\x04\x87\x01\
    \x18\x20\n\x0b\n\x03\x07F\x03\x12\x04\x87\x01#(\n\n\n\x02\x07G\x12\x04\
    \x88\x01\x08(\n\x0b\n\x03\x07G\x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\x07G\
    \x04\x12\x04\x88\x01\x08\x10\n\x0b\n\x03\x07G\x05\x12\x04\x88\x01\x11\
    \x17\n\x0b\n\x03\x07G\x01\x12\x04\x88\x01\x18\x1f\n\x0b\n\x03\x07G\x03\
    \x12\x04\x88\x01\"'\n\n\n\x02\x07H\x12\x04\x89\x01\x08*\n\x0b\n\x03\x07H\
    \x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\x07H\x04\x12\x04\x89\x01\x08\x10\n\
    \x0b\n\x03\x07H\x05\x12\x04\x89\x01\x11\x17\n\x0b\n\x03\x07H\x01\x12\x04\
    \x89\x01\x18!\n\x0b\n\x03\x07H\x03\x12\x04\x89\x01$)\n\n\n\x02\x07I\x12\
    \x04\x8b\x01\x08&\n\x0b\n\x03\x07I\x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\
    \x07I\x04\x12\x04\x8b\x01\x08\x10\n\x0b\n\x03\x07I\x05\x12\x04\x8b\x01\
    \x11\x15\n\x0b\n\x03\x07I\x01\x12\x04\x8b\x01\x16\x1d\n\x0b\n\x03\x07I\
    \x03\x12\x04\x8b\x01\x20%\n\n\n\x02\x07J\x12\x04\x8c\x01\x08*\n\x0b\n\
    \x03\x07J\x02\x12\x04\x80\x01\x07#\n\x0b\n\x03\x07J\x04\x12\x04\x8c\x01\
    \x08\x10\n\x0b\n\x03\x07J\x05\x12\x04\x8c\x01\x11\x15\n\x0b\n\x03\x07J\
    \x01\x12\x04\x8c\x01\x16!\n\x0b\n\x03\x07J\x03\x12\x04\x8c\x01$)\n\n\n\
    \x02\x07K\x12\x04\x8d\x01\x08)\n\x0b\n\x03\x07K\x02\x12\x04\x80\x01\x07#\
    \n\x0b\n\x03\x07K\x04\x12\x04\x8d\x01\x08\x10\n\x0b\n\x03\x07K\x05\x12\
    \x04\x8d\x01\x11\x15\n\x0b\n\x03\x07K\x01\x12\x04\x8d\x01\x16\x20\n\x0b\
    \n\x03\x07K\x03\x12\x04\x8d\x01#(\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
