name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        rust: [nightly]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install clippy rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt --toolchain nightly
      - name: Run
        run: |
          make clippy_check
          make fmt_check

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dep
      run: |
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers
        git checkout v2.0.6
        cmake .
        make
        sudo make install
        sudo ldconfig
        flatc --version
    
    - name: test
      run: make test

    - name: clean
      run: make clean

  integration-test:
    name: "Integration Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare Rust Builder
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ matrix.rust }}
      - name: Test
        shell: bash
        run: |
          bash ./query_server/test/script/start_and_test.sh

